pybo/views/mypage_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import AnswerForm
from ..models import Product

from flask import Flask, render_template, request, redirect, url_for
from flaskext.mysql import MySQL

from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from .. import db
from ..models import Question, Review, Answer, User, question_voter
from ..forms import QuestionForm, AnswerForm
from pybo.views.auth_views import login_required
from sqlalchemy import func

mysql = MySQL()
bp = Blueprint('mypage', __name__, url_prefix='/mypage')

@bp.route('/')
def main():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())

    return render_template('mypage/mypage_writtenquestion.html', user=g.user, product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/writtenquestion')
def writtenquestion():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())
    return render_template('mypage/mypage_writtenquestion.html', user=g.user, product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/recommendproduct')
def recommendproduct():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())
    return render_template('mypage/mypage_recommendproduct.html', user=g.user, product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/recommendquestion')
def recommendquestion():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())
    return render_template('mypage/mypage_recommendquestion.html', user=g.user,product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/writtenreview')
def writtenreview():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())

    return render_template('mypage/mypage_writtenreview.html', user=g.user, product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/writtenanswer')
def writtenanswer():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())

    return render_template('mypage/mypage_writtenanswer.html', user=g.user,product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/recommendreview')
def recommendreview():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())

    return render_template('mypage/mypage_recommendreview.html', user=g.user,product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

pybo/templates/mypage/mypage.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
{% include 'mypage/mypage_navbar.html' %}


</div>
{% endblock %}

pybo/templates/mypage/mypage_navbar.html
<div class="mypage_nav">

    <div class="my_info">
        <img style="width: 75px; height: 75px; position: absolute;" src="{{ url_for('static', filename = '/img/profile.png') }}" alt="profile">
        <div style="margin-left: 90px;">
            <div style="margin-top: 15px; margin-bottom: 5px;">
                <span style="font-size: 18px; margin-right: 12px;"><strong>{{ user.username }}</strong></span>
            </div>
            <div style="position:relative; margin: 10px 0px">
                {% if question_list %}
                {% set count = namespace(value=0) %}
                    {% for question in question_list %}
                    {% if user.id == question.user_id %}
                        {% set count.value = count.value + 1 %}
                    {% endif %}
                    {% endfor %}
                    <span style="">작성글 <strong> {{ count.value }}</strong></span>
                {% endif %}

                    {% if review_list %}
                    {% set count = namespace(value=0) %}
                    {% for review in review_list %}
                    {% if user.id == review.user_id %}
                         {% set count.value = count.value + 1 %}
                    {% endif %}
                    {% endfor %}
                        <span style="margin-left: 20px">작성 후기 <strong> {{ count.value }}</strong></span>
                    {% endif %}
            </div>
        </div>
    </div>



      <div class="mypage_option">
        <div class="">
            <a class="list_link" href="{{ url_for('mypage.writtenquestion') }}">
                작성글
            </a>
            <a class="list_link" href="{{ url_for('mypage.writtenreview') }}">
                작성 후기
            </a>
            <a class="list_link" href="{{ url_for('mypage.writtenanswer') }}">
                작성 댓글
            </a>
             <a class="list_link" href="{{ url_for('mypage.recommendquestion') }}">
                좋아요한 글
            </a>
            <a class="list_link" href="{{ url_for('mypage.recommendproduct') }}">
                좋아요한 제품
            </a>
            <a class="list_link" href="{{ url_for('mypage.recommendreview') }}">
                좋아요한 후기
            </a>
        </div>
      </div>


</div>

pybo/templates/mypage/mypage_recommendproduct.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
{% include 'mypage/mypage_navbar.html' %}


    {% if product_list %}
    {% set count = namespace(value=0) %}
    {% for product in product_list %}
    {% for voter in product.voter %}
    {% if voter == user %}

    {% set count.value = count.value + 1 %}

    {% endif %}
    {% endfor %}
    {% endfor %}

    <h5 class="link_mypage"><strong>좋아요한 제품 {{ count.value }}개</strong></h5>
    {%endif %}

    <div class="recommend_product">
         {% if product_list %}
        <div class="row">
            {% for product in product_list %}
                {% for voter in product.voter %}
                {% if voter == user %}
                     <div class="col-md-3">
                        <a class="card list-card" href="{{ url_for('product.detail', product_id=product.id) }}">
                            <div class="card-value">
                                <div class="sub">{{ product.subject }}</div>
                                <div class="cont">{{ product.content }}</div>
                                <div class="cont"><i class="fa-solid fa-heart"></i> {{ product.voter|length }}</div>
                            </div>
                            <img src="{{ url_for('static', filename = 'product_img/'+ product.address) }}" alt=""
                                 class="card-img"/>
                        </a>
                    </div>
                {% endif %}
            {% endfor %}
            {% endfor %}
            {% endif %}
        </div>
    </div>

</div>
{% endblock %}

pybo/templates/mypage/mypage_recommendquestion.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
{% include 'mypage/mypage_navbar.html' %}

    {% if question_list %}
        {% set count = namespace(value=0) %}
        {% for question in question_list %}
        {% for voter in question.voter %}
        {% if voter == user %}
            {% set count.value = count.value + 1 %}
        {% endif %}
        {% endfor %}
        {% endfor %}
         <h5 class="link_mypage"><strong>좋아요한 글 {{ count.value }}개</strong></h5>
    {% endif %}


     <div class="recommend_question" style="font-size: 13px">
          <table class="table">
        <thead>
        <tr class="text-center list_category">
            <th>번호</th>
            <th>편의점</th>
            <th style="width:50%">제목</th>
            <th>추천</th>
            <th>아이디</th>
            <th>작성일</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        {% for voter in question.voter %}
        {% if voter == user %}
        <tr >
            <td class="text-center">{{ question.id }}</td>
            <td class="text-center">{{ question.category }}</td>
            <td class="text-left">
                <a href="{{ url_for('question.detail', question_id=question.id) }}" style="text-decoration: none; color: black">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set|length }}</span>
                {% endif %}
            </td>
            <td class="text-center">{{ question.voter|length }}</td>
            <td class="text-center">{{ question.user.username }}</td>  <!-- 글쓴이 추가 -->
            <td class="text-center">{{ question.create_date|datetime}}</td>
        </tr>
        {% endif %}
        {% endfor %}
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">내용이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    </div>

</div>
{% endblock %}

pybo/templates/mypage/mypage_recommendreview.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
{% include 'mypage/mypage_navbar.html' %}

    {% if review_list %}
        {% set count = namespace(value=0) %}
        {% for review in review_list %}
        {% for voter in review.voter %}
        {% if voter == user %}
            {% set count.value = count.value + 1 %}
        {% endif %}
        {% endfor %}
        {% endfor %}
         <h5 class="link_mypage"><strong>좋아요한 후기 {{ count.value }}개</strong></h5>
    {% endif %}


     <div class="recommend_review" style="font-size: 13px">
          <table class="table">
        <thead>
        <tr class="text-center list_category">
            <th>번호</th>
            <th>제품명</th>
            <th style="width:50%">내용</th>
            <th>추천</th>
            <th>작성일</th>
        </tr>
        </thead>
        <tbody>
        {% if review_list %}
        {% for review in review_list %}
        {% for voter in review.voter %}
        {% if voter == user %}
        <tr >
            <div>
                <a href="{{ url_for('product.detail', product_id=review.product_id) }}" style="text-decoration: none; color: black">
            </div>
            <td class="text-center">{{ review.id }}</td>
            <td class="text-center">
                 {% if product_list %}
                {% for product in product_list %}
                {% if review.product_id == product.id %}
                    <a href="{{ url_for('product.detail', product_id=product.id) }}" style="text-decoration: none; color: black">{{ product.subject }}</a>
                {% endif %}
                {% endfor %}

                {% endif %}
            </td>
            <td class="text-center">{{ review.content }}</td>
            <td class="text-center">{{ review.voter|length }}</td>
            <td class="text-center">{{ review.create_date|datetime}}</td>
        </tr>
        {% endif %}
        {% endfor %}
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">내용이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    </div>

</div>
{% endblock %}

pybo/templates/mypage/mypage_writtenanswer.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
{% include 'mypage/mypage_navbar.html' %}


    {% if answer_list %}
    {% set count = namespace(value=0) %}
        {% for answer in answer_list %}
        {% if user.id == answer.user_id %}
            {% set count.value = count.value + 1 %}
        {% endif %}
        {% endfor %}
    <h5 class="link_mypage"><strong>작성 후기 {{ count.value }}개</strong></h5>
    {% endif %}

    <div class="recommend_product" style="font-size: 13px">
          <table class="table">
        <thead>
        <tr class="text-center list_category">
            <th>번호</th>
            <th>제품번호</th>
            <th style="width:50%">내용</th>
            <th>작성일</th>
        </tr>
        </thead>
        <tbody>
        {% if answer_list %}
        {% for answer in answer_list %}
        {% if user.id == answer.user_id %}
        <tr>
            <td class="text-center">{{ answer.question_id }}</td>
            <td>
                {% if question_list %}
                {% for question in question_list %}
                {% if answer.question_id == question.id %}
                    {{ question.subject }}
                {% endif %}
                {% endfor %}
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{{ url_for('question.detail', question_id=answer.question_id) }}" style="text-decoration: none; color: black">{{ answer.subject }}</a>
            </td>
            <td class="text-center">{{ answer.create_date|datetime}}</td>
        </tr>
        {% endif %}
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">내용이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

pybo/templates/mypage/mypage_writtenquestion.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
{% include 'mypage/mypage_navbar.html' %}


    {% if question_list %}
    {% set count = namespace(value=0) %}
        {% for question in question_list %}
        {% if user.id == question.user_id %}
            {% set count.value = count.value + 1 %}
        {% endif %}
        {% endfor %}
        <h5 class="link_mypage"><strong>작성글 {{ count.value }}개</strong></h5>
    {% endif %}


     <div class="written_question" style="font-size: 13px">
          <table class="table">
        <thead>
        <tr class="text-center list_category">
            <th>번호</th>
            <th>편의점</th>
            <th style="width:50%">제목</th>
            <th>추천</th>
            <th>작성일</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        {% if user.id == question.user_id %}
        <tr>
            <td class="text-center">{{ question.id }}</td>
            <td class="text-center">{{ question.category }}</td>
            <td class="text-left">
                <a href="{{ url_for('question.detail', question_id=question.id) }}" style="text-decoration: none; color: black">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set|length }}</span>
                {% endif %}
            </td>
            <td class="text-center">{{ question.voter|length }}</td>
            <td class="text-center">{{ question.create_date|datetime}}</td>
        </tr>
        {% endif %}
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">내용이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    </div>


</div>
{% endblock %}

pybo/templates/mypage/mypage_writtenreview.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
{% include 'mypage/mypage_navbar.html' %}


    {% if review_list %}
    {% set count = namespace(value=0) %}
    {% for review in review_list %}
    {% if user.id == review.user_id %}
         {% set count.value = count.value + 1 %}
    {% endif %}
    {% endfor %}
        <h5 class="link_mypage"><strong>작성 후기 {{ count.value }}개</strong></h5>
    {% endif %}

    <div class="recommend_product" style="font-size: 13px">
          <table class="table">
        <thead>
        <tr class="text-center list_category">
            <th>번호</th>
            <th>제품명</th>
            <th style="width:50%">내용</th>
            <th>작성일</th>
        </tr>
        </thead>
        <tbody>
        {% if review_list %}
        {% for review in review_list %}
        {% if user.id == review.user_id %}
        <tr>
            <td class="text-center">{{ review.id }}</td>
            <td>
                {% if product_list %}
                {% for product in product_list %}
                {% if review.product_id == product.id %}
                    {{ product.subject }}
                {% endif %}
                {% endfor %}
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{{ url_for('product.detail', product_id=review.product_id) }}" style="text-decoration: none; color: black">{{ review.content }}</a>
            </td>
            <td class="text-center">{{ review.create_date|datetime}}</td>
        </tr>
        {% endif %}
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">내용이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}