pybo/views/product_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from sqlalchemy import union

from .. import db
from ..models import Product
from ..forms import QuestionForm, AnswerForm

from pybo.views.auth_views import login_required


bp = Blueprint('product', __name__, url_prefix='/product')


@bp.route('/heyroo/')
def heyroo():
    category = 'heyroo'
    page = request.args.get('page', type=int, default=1)  # 페이지
    product_list = Product.query.filter(Product.category == category).order_by(Product.id.desc(), Product.create_date.desc())
    product_list = product_list.paginate(page, per_page=12)
    return render_template('product/product_list.html', product_list=product_list, user=g.user, category=category)

@bp.route('/youus/')
def youus():
    category = 'youus'
    page = request.args.get('page', type=int, default=1)  # 페이지
    product_list = Product.query.filter(Product.category == category).order_by(Product.id.desc(), Product.create_date.desc())
    product_list = product_list.paginate(page, per_page=12)
    return render_template('product/product_list.html', product_list=product_list, user=g.user, category=category)

@bp.route('/sselect/')
def sselect():
    category = 'sselect'
    page = request.args.get('page', type=int, default=1)  # 페이지
    product_list = Product.query.filter(Product.category == category).order_by(Product.id.desc(), Product.create_date.desc())
    product_list = product_list.paginate(page, per_page=12)
    return render_template('product/product_list.html', product_list=product_list, user=g.user, category=category)

@bp.route('/minist/')
def minist():
    category = 'minist'
    page = request.args.get('page', type=int, default=1)  # 페이지
    product_list = Product.query.filter(Product.category == category).order_by(Product.id.desc(), Product.create_date.desc())
    product_list = product_list.paginate(page, per_page=12)
    return render_template('product/product_list.html', product_list=product_list, user=g.user, category=category)

@bp.route('/detail/<int:product_id>/')
def detail(product_id):
    form = AnswerForm()
    product = Product.query.get_or_404(product_id)
    category = product.category
    product_list = Product.query.filter(Product.category == category).filter(Product.id != product_id).order_by(Product.id.desc(), Product.create_date.desc())
    return render_template('product/product_detail.html', product=product, form=form, user=g.user, product_list=product_list, category=category)

@bp.route('/vote/<int:product_id>/')
@login_required
def vote(product_id):
    _product = Product.query.get_or_404(product_id)
    if g.user == _product.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        _product.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('product.detail', product_id=product_id))

pybo/views/review_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import AnswerForm
from ..models import Product, Review
from .auth_views import login_required

bp = Blueprint('review', __name__, url_prefix='/review')

@bp.route('/create/<int:product_id>', methods=('POST',))
@login_required
def create(product_id):
    form = AnswerForm()
    product = Product.query.get_or_404(product_id)
    if form.validate_on_submit():
        content = request.form['content']
        review = Review(content=content, create_date=datetime.now(), user=g.user)
        product.review_set.append(review)
        db.session.commit()
        return redirect(url_for('product.detail', product_id=product_id))
    return render_template('product/product_detail.html', product=product, form=form, user=g.user)

@bp.route('/modify/<int:review_id>', methods=('GET', 'POST'))
@login_required
def modify(review_id):
    review = Review.query.get_or_404(review_id)
    if g.user != review.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('product.detail', product_id=review.product.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(review)
            review.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('product.detail', product_id=review.product.id))
    else:
        form = AnswerForm(obj=review)
    return render_template('answer/answer_form.html', form=form, user=g.user)

@bp.route('/delete/<int:review_id>')
@login_required
def delete(review_id):
    review = Review.query.get_or_404(review_id)
    product_id = review.product.id
    if g.user != review.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(review)
        db.session.commit()
    return redirect(url_for('product.detail', product_id=product_id))

@bp.route('/vote/<int:review_id>/')
@login_required
def vote(review_id):
    _review = Review.query.get_or_404(review_id)
    if g.user == _review.user:
        flash('본인이 작성한 글은 좋아요 할 수 없습니다')
    else:
        _review.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('product.detail', product_id=_review.product.id))

pybo/templates/product/product_banner.html
<img src="{{ url_for('static', filename = 'brand/' + category + '_banner.jpg') }}" class="banner_img"/>
<hr class="nav_hr">

<!--{% if category =='heyroo'%}-->
<!--<div>-->
<!--    <div class="banner_title">HEYROO</div>-->
<!--    <div class="banner_content">'HEYROO'는 CU의 PB 브랜드로 꼭 필요한 것들만 골라 커다란 주머니에 담은 캥거루를 모티브로 했습니다.</div>-->
<!--    <div class="banner_content2">친근한 인사말 HEY와 캥거루를 상징하는 ROO의 합성어로 ‘정성스럽게 가치를 담아 전달하는 좋은 친구’라는 의미입니다.</div>-->
<!--</div>-->
<!--{% elif category =='youus'%}-->
<!--<div>-->
<!--    <div class="banner_title">YOUUS</div>-->
<!--    <div class="banner_content2">'YOUUS'는 YOU(고객)와 US(고객+GS리테일)의 합성어로 고객과 GS리테일이 하나 되는 마음으로 선택한 상품이라는 의미를 담고 있습니다.</div>-->
<!--</div>-->
<!--{% elif category =='sselect'%}-->
<!--<div>-->
<!--    <div class="banner_title">7-SELECT</div>-->
<!--    <div class="banner_content2">'7-SELECT'는 좋은 품질, 합리적인 가격의 상품을 골라 고객에게 제공하겠다는 의미가 담겨있습니다.</div>-->
<!--</div>-->
<!--{% elif category =='minist'%}-->
<!--<div>-->
<!--    <div class="banner_title">MIN1ST</div>-->
<!--    <div class="banner_content2">'MIN1ST'는 미니스톱의 첫 번째 대표상품임을 알리는 동시에 고객에게 최고의 만족을 줄 수 있는 상품이라는 의미를 담았습니다.</div>-->
<!--</div>-->
<!--{% endif %}-->

pybo/templates/product/product_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <h1 class="PBTitle"></h1>
    <div class="ProductContainer">
        <div class="inner">
            <div class="product_view">
                <div class="product_img">
                    <img id="image" src="{{ url_for('static', filename = 'product_img/'+ product.address) }}"
                         alt="{{ product.subject }}"
                         width="300px" height="300px" style="margin: 60px 40px;">
                </div>

                <div class="product_content">
                    <dl>
                        <dt>
                            <span class="product_name">{{ product.subject }}</span>
                        </dt>
                        <dd class="content_dd_01">
                            <ul class="txt">
                                <li>
                                    {{ product.explaination }}
                                </li>
                            </ul>
                        </dd>
                        <dd class="content_dd_02">
                            <a href="javascript:void(0)" data-uri="{{ url_for('product.vote', product_id=product.id) }}"
                               class="recommend recommend_style">
                                <!--<img style="width: 15px; height: 15px; margin-bottom: 4px"-->
                                <!--src="{{ url_for('static', filename = '/brand/recommend.png') }}" alt="recommend">-->
                                <i class="fa-solid fa-heart"></i>
                                <span style="margin-left: 5px">좋아요</span>
                                <span>{{ product.voter|length }}</span>
                            </a>
                            <a href="#" class="recommend_style" style="margin-left: 12px">
                                <i class="fa-regular fa-comment-dots"></i>
                                <span style="margin-left: 5px">댓글</span>
                                <span>{{ product.review_set|length }}</span>
                            </a>
                            <span class="product_price">
                                    <strong>{{ product.content }}</strong>
                                </span>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>


    <!-- 답변 목록 -->
    <div class="comment_container">
        <h5><strong>후기 {{ product.review_set|length }}개</strong></h5>
        {% for review in product.review_set %}
        <ul style="list-style: none; padding-left: 0px; margin-bottom: 0px; width: 960px">
            <div class="review_inner">
                <li class="comment_item">
                    <div class="comment_body">
                        <img class="comment_profile" src="{{ url_for('static', filename = '/img/profile.png') }}"
                             alt="profile">
                        <div class="comment_box">
                            <div class="comment_nick_setting">
                                <span style="font-size: 18px; margin-right: 12px;">{{ review.user.username }}</span>
                                {% if review.modify_date %}
                                <span style="margin-right: 8px">modified at</span>
                                <span>{{ review.modify_date|datetime }}</span>
                                {% else %}
                                <span>{{ review.create_date|datetime }}</span>
                                {% endif %}
                                <div class="modify_box">
                                    {% if g.user == review.user %}
                                    <a href="{{ url_for('review.modify', review_id=review.id) }}"
                                       class="modify_btn">수정</a>
                                    <a href="#" class="delete delete_btn"
                                       data-uri="{{ url_for('review.delete', review_id=review.id) }}">삭제</a>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="comment_box_text">{{ review.content }}</div>
                            <div class="comment_recommend">
                                <a href="javascript:void(0)"
                                   data-uri="{{ url_for('review.vote', review_id=review.id) }}"
                                   class="recommend recommend_style">
                                    <!--                                    <img style="width: 15px; height: 15px; margin-bottom: 4px" src="{{ url_for('static', filename = '/brand/recommend.png') }}" alt="recommend">-->
                                    <i class="fa-solid fa-heart"></i>
                                    <span style="margin-left: 5px">좋아요</span>
                                    <span>{{ review.voter|length }}</span>
                                </a>
                            </div>
                        </div>
                </li>
            </div>
        </ul>
        {% endfor %}
    </div>

    <!-- 답변 등록 -->
    <div class="comment_cont">
        <div class="comment_div">
            <!-- 오류표시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field, errors in form.errors.items() %}
                <strong>{{ form[field].label }}</strong>
                <ul>
                    {% for error in errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="CommentWriter">
                <form action="{{ url_for('review.create', product_id=product.id) }}" method="post" class="form">
                    {{ form.csrf_token }}
                    <div class="comment_inner1">
                        {% if not g.user %}
                        <em class="comment_name">로그인 후 이용해주세요.</em>
                        {% endif %}
                        <em class="comment_name">{{ g.user.username }}</em>
                        <textarea {% if not g.user %}disabled{% endif %} name="content" id="content"
                                  class="comment_text" placeholder="후기를 입력해주세요."></textarea>
                    </div>
                    <div class="comment_inner2">
                        <div class="register_box">
                            <input type="submit" value="답변등록" class="submit_button">
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <div class="row my-5">
        <div class="visual_area2">다른 상품 보기</div>
        {% set count = namespace(value=0) %}
        {% for p in product_list %}
        {% if p.id >= product.id %}
        {% set count.value = count.value + 1 %}
        {% elif p.id < product.id and loop.index <= count.value + 4%}
        <div class="col-md-3">
            <a class="card list-card" href="{{ url_for('product.detail', product_id=p.id) }}">
                <div class="card-value">
                    <div class="sub">{{ p.subject }}</div>
                    <div class="cont">{{ p.content }}</div>
                    <div class="cont"><i class="fa-solid fa-heart"></i> {{ p.voter|length }}</div>
                </div>
                <img src="{{ url_for('static', filename = 'product_img/'+ p.address) }}" alt="" class="card-img"/>
            </a>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endblock %}
    {% block script %}
    <script type='text/javascript'>
        const delete_elements = document.getElementsByClassName("delete");
        Array.from(delete_elements).forEach(function (element) {
            element.addEventListener('click', function () {
                if (confirm("정말로 삭제하시겠습니까?")) {
                    location.href = this.dataset.uri;
                }
                ;
            });
        });
        const recommend_elements = document.getElementsByClassName("recommend");
        Array.from(recommend_elements).forEach(function (element) {
            element.addEventListener('click', function () {
                if (confirm("정말로 좋아요 하시겠습니까?")) {
                    location.href = this.dataset.uri;
                }
                ;
            });
        });
    </script>
    {% endblock %}

pybo/templates/product/product_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    {% include "product/product_banner.html" %}
    <div class="row">
        {% if product_list %}
        {% for product in product_list.items %}
        {% if product.category == category %}
        <div class="col-md-3">
            <a class="card list-card" href="{{ url_for('product.detail', product_id=product.id) }}">
                <div class="card-value">
                    <div class="sub">{{ product.subject }}</div>
                    <div class="cont">{{ product.content }}</div>
                    <div class="cont"><i class="fa-solid fa-heart"></i> {{ product.voter|length }}</div>
                </div>
                <img src="{{ url_for('static', filename = 'product_img/'+ product.address) }}" alt=""
                     class="card-img"/>
            </a>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if product_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ product_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in product_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != product_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if product_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ product_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}