pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import AnswerForm
from ..models import Question, Answer
from .auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect('{}#answer_{}'.format(
            url_for('question.detail', question_id=question_id), answer.id))
    return render_template('question/question_detail.html', question=question, form=form, user=g.user)

@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect('{}#answer_{}'.format(
                url_for('question.detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)

@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

@bp.route('/vote/<int:answer_id>/')
@login_required
def vote(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        _answer.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=_answer.question.id))

pybo/views/comment_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import CommentForm
from pybo.models import Question, Comment, Answer
from pybo.views.auth_views import login_required

bp = Blueprint('comment', __name__, url_prefix='/comment')


@bp.route('/create/question/<int:question_id>', methods=('GET', 'POST'))
@login_required
def create_question(question_id):
    form = CommentForm()
    question = Question.query.get_or_404(question_id)
    if request.method == 'POST' and form.validate_on_submit():
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), question=question)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('comment/comment_form.html', form=form, user=g.user)


@bp.route('/modify/question/<int:comment_id>', methods=('GET', 'POST'))
@login_required
def modify_question(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=comment.question.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=comment.question.id))
    else:
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html', form=form)


@bp.route('/delete/question/<int:comment_id>')
@login_required
def delete_question(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    question_id = comment.question.id
    if g.user != comment.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))


@bp.route('/create/answer/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def create_answer(answer_id):
    form = CommentForm()
    answer = Answer.query.get_or_404(answer_id)
    if request.method == 'POST' and form.validate_on_submit():
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), answer=answer)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=answer.question.id))
    return render_template('comment/comment_form.html', form=form, user=g.user)


@bp.route('/modify/answer/<int:comment_id>', methods=('GET', 'POST'))
@login_required
def modify_answer(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=comment.answer.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=comment.answer.question.id))
    else:
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html', form=form)


@bp.route('/delete/answer/<int:comment_id>')
@login_required
def delete_answer(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    question_id = comment.answer.question.id
    if g.user != comment.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from .. import db
from ..models import Question, Answer, User, question_voter
from ..forms import QuestionForm, AnswerForm
from pybo.views.auth_views import login_required
from sqlalchemy import func

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    so = request.args.get('so', type=str, default='recent')
    # ca = request.args.get('ca', type=str, default='')

    if so == 'recommend':
        sub_query = db.session.query(
            question_voter.c.question_id, func.count('*').label('num_voter')) \
            .group_by(question_voter.c.question_id).subquery()
        question_list = Question.query \
            .outerjoin(sub_query, Question.id == sub_query.c.question_id) \
            .order_by(sub_query.c.num_voter.desc(), Question.create_date.desc())
    elif so == 'popular':
        sub_query = db.session.query(
            Answer.question_id, func.count('*').label('num_answer')) \
            .group_by(Answer.question_id).subquery()
        question_list = Question.query \
            .outerjoin(sub_query, Question.id == sub_query.c.question_id) \
            .order_by(sub_query.c.num_answer.desc(), Question.create_date.desc())
    elif so == 'old':
        question_list = Question.query.order_by(Question.create_date.asc())

    elif so == 'recent':
        question_list = Question.query.order_by(Question.create_date.desc())
    # else:
    #     question_list = Question.query.order_by(Question.create_date.desc())
    # 2022.0603 카테고리 정렬 중 questio_list가 if문 중 하나만 인식하는 오류가 생김
    elif so == 'CU':
        question_list = Question.query.filter_by(category='CU')

    elif so == 'GS25':
        question_list = Question.query.filter_by(category='GS25')
    elif so == '미니스탑':
        question_list = Question.query.filter_by(category='미니스탑')

    elif so == '세븐일레븐':
        question_list = Question.query.filter_by(category='세븐일레븐')
    else:
        question_list = Question.query.order_by(Question.create_date.desc())

    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        question_list = question_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(Question.subject.ilike(search) |  # 질문제목
                    Question.category.ilike(search) |  # 질문카테고리
                    Question.content.ilike(search) |  # 질문내용
                    User.username.ilike(search) |  # 질문작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw, so=so, user=g.user)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    page = request.args.get('page', type=int, default=1)
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    # answer = Answer.query.order_by(question.answer_set)
    answer = Answer.query.order_by(Answer.create_date.desc())
    pagination = answer.paginate(page, per_page=5)
    return render_template('question/question_detail.html', question=question, form=form, pagination=pagination, user=g.user)


@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, category=form.category.data, content=form.content.data,
                            create_date=datetime.now(),
                            user=g.user)

        db.session.add(question)
        db.session.commit()
        return redirect(url_for('question._list'))
    return render_template('question/question_form.html', form=form, user=g.user)


@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)


@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))


@bp.route('/vote/<int:question_id>/')
@login_required
def vote(question_id):
    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/questions_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import QuestionsForm, AnswerForm
from pybo.models import Questions , Answers, User
from pybo.views.auth_views import login_required

bp = Blueprint('questions', __name__, url_prefix='/questions')


@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    questions_list = Questions.query.order_by(Questions.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answers.questions_id, Answers.content, User.username) \
            .join(User, Answers.user_id == User.id).subquery()
        questions_list = questions_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.questions_id == Questions.id) \
            .filter(Questions.subject.ilike(search) |  # 질문제목
                    Questions.content.ilike(search) |  # 질문내용
                    User.username.ilike(search) |  # 질문작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()
    questions_list = questions_list.paginate(page, per_page=10)
    return render_template('questions/questions_list.html', questions_list=questions_list, page=page, kw=kw, user=g.user)

@bp.route('/detail/<int:questions_id>/')
def detail(questions_id):
    form = AnswerForm()
    questions = Questions.query.get_or_404(questions_id)
    return render_template('questions/questions_detail.html', questions=questions, form=form, user=g.user)


@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = QuestionsForm()
    if request.method == 'POST' and form.validate_on_submit():
        questions = Questions(subject=form.subject.data, content=form.content.data, category=form.category.data,
                            create_date=datetime.now(), user=g.user)
        db.session.add(questions)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('questions/questions_form.html', form=form, user=g.user)


@bp.route('/modify/<int:questions_id>', methods=('GET', 'POST'))
@login_required
def modify(questions_id):
    questions = Questions.query.get_or_404(questions_id)
    if g.user != questions.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=questions_id, user=g.user))
    if request.method == 'POST':  # POST 요청
        form = QuestionsForm()
        if form.validate_on_submit():
            form.populate_obj(questions)
            questions.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('questions.detail', question_id=questions_id, user=g.user))
    else:  # GET 요청
        form = QuestionsForm(obj=questions)
    return render_template('questions/questions_form.html', form=form, user=g.user)


@bp.route('/delete/<int:questions_id>')
@login_required
def delete(questions_id):
    questions = Questions.query.get_or_404(questions_id)
    if g.user != questions.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('questions.detail', questions_id=questions_id, user=g.user))
    db.session.delete(questions)
    db.session.commit()
    return redirect(url_for('questions._list'))


@bp.route('/vote/<int:questions_id>/')
@login_required
def vote(questions_id):
    questions = Questions.query.get_or_404(questions_id)
    if g.user == questions.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        questions.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('questions.detail', question_id=questions_id, user=g.user))

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <div class="question_container">
        <div style="color: gray">
            Category : {{ question.category }}
        </div>
        <div class="question_info">
            <h2 class="py-2">{{ question.subject }}</h2>
            <div class="comment_body">
                <img class="comment_profile" src="{{ url_for('static', filename = '/img/profile.png') }}" alt="profile">
                <div class="comment_box">
                    <span style="font-size: 18px; margin-right: 12px;"><strong>{{ question.user.username }}</strong></span>
                    <div class="modify_box">
                        {% if g.user == question.user %}
                        <a href="{{ url_for('question.modify', question_id=question.id) }}" class="modify_btn">수정</a>
                        <a href="#" class="delete delete_btn"
                           data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
                        {% endif %}
                    </div>
                    <div class="comment_box_text">
                        {% if question.modify_date %}
                        <span style="margin-right: 8px">modified at</span>
                        <span>{{ question.modify_date }}</span>
                        {% else %}
                        <span>{{ question.create_date|datetime}}</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="question_content" style="margin: 70px 0px">
            <div class="comment_box_text">{{ question.content|markdown }}</div>
        </div>
        <div class="question_recommend">
            <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}"
               class="recommend recommend_style">
                <i class="fa-solid fa-heart"></i>
                <span style="margin-left: 5px">좋아요</span>
                <span>{{ question.voter|length }}</span>
            </a>
            <a href="#" class="recommend_style" style="margin-left: 12px">
                <i class="fa-regular fa-comment-dots"></i>
                <span style="margin-left: 5px">댓글</span>
                <span>{{ question.answer_set|length }}</span>
            </a>
        </div>
    </div>


    <!-- 답변 목록 -->
    <div class="comment_container">
        <h5><strong>댓글 {{ question.answer_set|length }}개</strong></h5>
        {% for answer in question.answer_set %}
        <ul style="list-style: none; padding-left: 0px; margin-bottom: 0px; width: 960px">
            <div class="review_inner">
                <li class="comment_item">
                    <div class="comment_body">
                        <img class="comment_profile" src="{{ url_for('static', filename = '/img/profile.png') }}"
                             alt="profile">
                        <div class="comment_box">
                            <span style="font-size: 18px; margin-right: 12px;"><strong>{{ answer.user.username }}</strong></span>
                            {% if answer.modify_date %}
                            <span style="margin-right: 8px">modified at</span>
                            <span>{{ answer.modify_date }}</span>
                            {% else %}
                            <span>{{ answer.create_date|datetime }}</span>
                            {% endif %}
                            <div class="modify_box">
                                {% if g.user == answer.user %}
                                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}" class="modify_btn">수정</a>
                                <a href="#" class="delete delete_btn"
                                   data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                                {% endif %}
                            </div>
                            <div class="comment_box_text">{{ answer.content|markdown }}</div>
                            <div class="comment_recommend">
                                <a href="javascript:void(0)"
                                   data-uri="{{ url_for('answer.vote', answer_id=answer.id) }}"
                                   class="recommend recommend_style">
                                    <i class="fa-solid fa-heart"></i>
                                    <span style="margin-left: 5px">좋아요</span>
                                    <span>{{ answer.voter|length }}</span>
                                    <div style="margin-top: 2px">
                                        <a href="{{ url_for('comment.create_answer', answer_id=answer.id) }}"
                                           class="recommend_style">댓글 추가 ..</a>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% if answer.comment_set|length > 0 %}
                    {% for comment in answer.comment_set %}
                    <a name="comment_{{ comment.id }}"></a>
                    <ul style="list-style: none; padding-left: 0px; border-top: 1.8px solid #dee2e6 !important;">
                        <div class="comment_of_comment_inner">
                            <li class="coc_item">
                                <div class="coc_body">
                                    <img class="comment_profile"
                                         src="{{ url_for('static', filename = '/img/profile.png') }}" alt="profile">
                                    <div class="coc_box">
                                        <span style="font-size: 18px; margin-right: 12px;"><strong>{{ comment.user.username }}</strong></span>
                                        {% if comment.modify_date %}
                                        <span style="margin-right: 8px">modified at</span>
                                        <span>{{ comment.modify_date|datetime }}</span>
                                        {% else %}
                                        <span>{{ comment.create_date|datetime }}</span>
                                        {% endif %}
                                        <div class="modify_box">
                                            {% if g.user == comment.user %}
                                            <a href="{{ url_for('comment.modify_answer', comment_id=comment.id) }}"
                                               class="modify_btn">수정</a>
                                            <a href="#" class="delete delete_btn"
                                               data-uri="{{ url_for('comment.delete_answer', comment_id=comment.id) }}">삭제</a>
                                            {% endif %}
                                        </div>
                                        <div class="comment_box_text">{{ comment.content }}</div>
                                        <div class="comment_recommend">
                                            <div>
                                                <a href="{{ url_for('comment.create_answer', answer_id=answer.id) }}"
                                                   class="recommend_style">댓글 추가 ..</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </div>
                    </ul>
                    {% endfor %}
                    {% endif %}
                    <!-- 답변 댓글 End -->
                </li>
            </div>
        </ul>
        {% endfor %}
    </div>


    <!-- 답변 등록 -->
    <div class="comment_cont">
        <div class="comment_div">
            <!-- 오류표시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field, errors in form.errors.items() %}
                <strong>{{ form[field].label }}</strong>
                <ul>
                    {% for error in errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="CommentWriter">
                <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="form">
                    {{ form.csrf_token }}
                    <div class="comment_inner1">
                        {% if not g.user %}
                        <em class="comment_name">로그인 후 이용해주세요.</em>
                        {% endif %}
                        <em class="comment_name">{{ g.user.username }}</em>
                        <textarea {% if not g.user %}disabled{% endif %} name="content"
                                  class="comment_text" placeholder="후기를 입력해주세요."></textarea>
                    </div>
                    <div class="comment_inner2">
                        <div class="register_box">
                            <input type="submit" value="답변등록" class="submit_button">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if pagination.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ pagination.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in pagination.iter_pages() %}
        {% if page_num %}
        {% if page_num != pagination.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if pagination.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ pagination.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

    <div class="row">
        {% for p in product_list %}
        {% if p.id < product.id and p.id > (product.id-5) %}
        <div class="col-md-3">
            <a class="card list-card" href="{{ url_for('product.detail', product_id=p.id) }}">
                <div class="card-value">
                    <div class="sub">{{ p.subject }}</div>
                    <div class="cont">{{ p.content }}</div>
                    <div class="cont"><i class="fa-solid fa-heart"></i> {{ p.voter|length }}</div>
                </div>
                <img src="{{ url_for('static', filename = 'product_img/'+ p.address) }}" alt="" class="card-img"/>
            </a>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            if (confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            }
            ;
        });
    });

    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            if (confirm("좋아요를 누르시겠습니까?")) {
                location.href = this.dataset.uri;
            }
            ;
        });
    });
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<!--<script>-->
<!--    $(document).ready(function(){-->
<!--        $("#content").summernote();-->
<!--    });-->
<!--</script>-->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">제안 하기</h5>
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.data or '' }}">
        </div>

        <div class="mb-3">
            <label for="category_i">카테고리</label>
            <select class="form-control" name="category" id="category_i"
                    value="{{ form.category.data or '' }}">
                <option>CU</option>
                <option>GS25</option>
                <option>미니스탑</option>
                <option>세븐일레븐</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10" placehold="내용을 입력하세요.">{{ form.content.data or '' }}</textarea>
        </div>
        <script>
                ClassicEditor
                    .create( document.querySelector( '#content'), {
                        language: {ui :'ko', content: 'ko' },
                    }).catch( error=> {
                    console.error(error);
                    });
            </script>

        <button type="submit" class="btn btn-warning">저장하기</button>
    </form>
</div>
{% endblock %}