pybo/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm

from pybo import db
from pybo.forms import UserCreateForm
from pybo.models import User

import functools


bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

pybo/views/map_view.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g
from werkzeug.utils import redirect

from .. import db
from ..models import Question, User
from ..forms import QuestionForm, AnswerForm

from pybo.views.auth_views import login_required

bp = Blueprint('map', __name__, url_prefix='/map')

@bp.route('/')
def map():
    return render_template('map/map.html', user=g.user)

pybo/views/mypage_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import AnswerForm
from ..models import Product

from flask import Flask, render_template, request, redirect, url_for
from flaskext.mysql import MySQL

from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from .. import db
from ..models import Question, Review, Answer, User, question_voter
from ..forms import QuestionForm, AnswerForm
from pybo.views.auth_views import login_required
from sqlalchemy import func

mysql = MySQL()
bp = Blueprint('mypage', __name__, url_prefix='/mypage')

@bp.route('/')
def main():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())

    return render_template('mypage/mypage_writtenquestion.html', user=g.user, product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/writtenquestion')
def writtenquestion():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())
    return render_template('mypage/mypage_writtenquestion.html', user=g.user, product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/recommendproduct')
def recommendproduct():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())
    return render_template('mypage/mypage_recommendproduct.html', user=g.user, product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/recommendquestion')
def recommendquestion():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())
    return render_template('mypage/mypage_recommendquestion.html', user=g.user,product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/writtenreview')
def writtenreview():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())

    return render_template('mypage/mypage_writtenreview.html', user=g.user, product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/writtenanswer')
def writtenanswer():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())

    return render_template('mypage/mypage_writtenanswer.html', user=g.user,product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

@bp.route('/recommendreview')
def recommendreview():
    product_list = Product.query.order_by(Product.id.desc())
    question_list = Question.query.order_by(Question.create_date.desc())
    answer_list = Answer.query.order_by(Answer.create_date.desc())
    review_list = Review.query.order_by(Review.create_date.desc())

    return render_template('mypage/mypage_recommendreview.html', user=g.user,product_list=product_list, question_list=question_list, review_list=review_list, answer_list=answer_list)

pybo/views/product_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from sqlalchemy import union

from .. import db
from ..models import Product
from ..forms import QuestionForm, AnswerForm

from pybo.views.auth_views import login_required


bp = Blueprint('product', __name__, url_prefix='/product')


@bp.route('/heyroo/')
def heyroo():
    category = 'heyroo'
    page = request.args.get('page', type=int, default=1)  # 페이지
    product_list = Product.query.filter(Product.category == category).order_by(Product.id.desc(), Product.create_date.desc())
    product_list = product_list.paginate(page, per_page=12)
    return render_template('product/product_list.html', product_list=product_list, user=g.user, category=category)

@bp.route('/youus/')
def youus():
    category = 'youus'
    page = request.args.get('page', type=int, default=1)  # 페이지
    product_list = Product.query.filter(Product.category == category).order_by(Product.id.desc(), Product.create_date.desc())
    product_list = product_list.paginate(page, per_page=12)
    return render_template('product/product_list.html', product_list=product_list, user=g.user, category=category)

@bp.route('/sselect/')
def sselect():
    category = 'sselect'
    page = request.args.get('page', type=int, default=1)  # 페이지
    product_list = Product.query.filter(Product.category == category).order_by(Product.id.desc(), Product.create_date.desc())
    product_list = product_list.paginate(page, per_page=12)
    return render_template('product/product_list.html', product_list=product_list, user=g.user, category=category)

@bp.route('/minist/')
def minist():
    category = 'minist'
    page = request.args.get('page', type=int, default=1)  # 페이지
    product_list = Product.query.filter(Product.category == category).order_by(Product.id.desc(), Product.create_date.desc())
    product_list = product_list.paginate(page, per_page=12)
    return render_template('product/product_list.html', product_list=product_list, user=g.user, category=category)

@bp.route('/detail/<int:product_id>/')
def detail(product_id):
    form = AnswerForm()
    product = Product.query.get_or_404(product_id)
    category = product.category
    product_list = Product.query.filter(Product.category == category).filter(Product.id != product_id).order_by(Product.id.desc(), Product.create_date.desc())
    return render_template('product/product_detail.html', product=product, form=form, user=g.user, product_list=product_list, category=category)

@bp.route('/vote/<int:product_id>/')
@login_required
def vote(product_id):
    _product = Product.query.get_or_404(product_id)
    if g.user == _product.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        _product.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('product.detail', product_id=product_id))

pybo/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="generator" content="Hugo 0.88.1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/navbars/">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='modify.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />
    <script src="{{ url_for('static', filename='jquery-3.5.1.min.js') }}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/34.1.0/classic/ckeditor.js"></script>
    <title>SSUPerB!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- 네비게이션바 -->
{% include "footer.html" %}
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='maptest.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='slick_set.js') }}"></script>
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="https://kit.fontawesome.com/b743324a50.js" crossorigin="anonymous"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

pybo/templates/footer.html
<div class="border-top">
    <div class="container">
        <footer class="row row-cols-4 py-3 my-3 ">
            <div class="col">
                <a href="#"><img src="{{ url_for('static', filename='/brand/brand_logo_38x25.png') }}"></a>
                <p class="text-muted">서울특별시 동작구 상도동 사당로 50 5층 507호 TEL:1588-1588</p>
                <p class="text-muted">COPYRIGHT &copy; SSUPerB <br>ALL RIGHT RESERVED.</p>
            </div>

            <div class="col"></div>
            <div class="col">
                <h5>Brand</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{{ url_for('product.heyroo') }}" class="nav-link p-0 text-muted">HEYROO</a>
                    </li>
                    <li class="nav-item mb-2"><a href="{{ url_for('product.youus') }}" class="nav-link p-0 text-muted">YOUUS</a>
                    </li>
                    <li class="nav-item mb-2"><a href="{{ url_for('product.sselect') }}"
                                                 class="nav-link p-0 text-muted">7-Select</a></li>
                    <li class="nav-item mb-2"><a href="{{ url_for('product.minist') }}" class="nav-link p-0 text-muted">Min1st</a>
                    </li>
                </ul>
            </div>

            <div class="col">
                <h5>Menu</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{{ url_for('question._list') }}" class="nav-link p-0 text-muted">제안게시판</a></li>
                    <li class="nav-item mb-2"><a href="{{ url_for('map.map') }}" class="nav-link p-0 text-muted">주변
                        편의점</a></li>
                    <li class="nav-item mb-2"><a href="{{ url_for('support.support') }}" class="nav-link p-0 text-muted">자주묻는질문</a></li>
                    <li class="nav-item mb-2"><a href="{{ url_for('questions._list') }}" class="nav-link p-0 text-muted">Q&A</a></li>
                </ul>
            </div>
        </footer>
    </div>
</div>

pybo/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pybo/templates/navbar.html
<!--&lt;!&ndash; 네비게이션바 &ndash;&gt;-->
<!--<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">-->
<!--    <div class="container-fluid">-->
<!--        <a class="navbar-brand" href="{{ url_for('main.index') }}">Pybo</a>-->
<!--        <button class="navbar-toggler" type="button"-->
<!--                data-bs-toggle="collapse"-->
<!--                data-bs-target="#navbarSupportedContent"-->
<!--                aria-controls="navbarSupportedContent"-->
<!--                aria-expanded="false"-->
<!--                aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--            {% if g.user %}-->
<!--            <ul class="navbar-nav">-->
<!--                <li class="nav-item ">-->
<!--                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>-->
<!--                </li>-->
<!--            </ul>-->
<!--            {% else %}-->
<!--            <ul class="navbar-nav me-auto mb-2 mb-lg-0">-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--        {% endif %}-->
<!--    </div>-->
<!--</nav>-->

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom" aria-label="Ninth navbar example">
    <div class="container-xl">
        <a class="navbar-brand" href="{{ url_for('main.index') }}"><img
                src="{{ url_for('static', filename='/brand/brand_logo_38x25.png') }}"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07XL"
                aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07XL">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link nav-border" href="{{ url_for('product.heyroo') }}">HEYROO</a></li>
                <li class="nav-item"><a class="nav-link nav-border" href="{{ url_for('product.youus') }}">YOUUS</a></li>
                <li class="nav-item"><a class="nav-link nav-border" href="{{ url_for('product.sselect') }}">7-Select</a></li>
                <li class="nav-item"><a class="nav-link nav-border" href="{{ url_for('product.minist') }}">Min1st</a></li>
                <li class="nav-item"><a class="nav-link nav-border" href="{{ url_for('map.map') }}">주변 편의점</a></li>
                <li class="nav-item"><a class="nav-link nav-border" href="{{ url_for('question._list') }}">제안게시판</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-bs-toggle="dropdown"
                       aria-expanded="false">고객지원</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown07XL">
                        <li><a class="dropdown-item" href="{{ url_for('support.support') }}">자주묻는질문</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('questions._list') }}">Q&A</a></li>
                    </ul>
                </li>
            </ul>
            <div class="text-end">
                {% if g.user %}
                <a type="text" class="btn nav-item" href="{{ url_for('mypage.main') }}">{{user.username}}</a>
                <a type="button" class="btn btn-warning" href="{{ url_for('auth.logout') }}">Logout</a>
                {% else %}
                <a type="button" class="btn btn-warning" href="{{ url_for('auth.login') }}">Login</a>
                <a type="button" class="btn btn-warning" href="{{ url_for('auth.signup') }}">Sign-up</a>
            </div>
            {% endif %}
            <!-- <form>
              <input class="form-control" type="text" placeholder="Search" aria-label="Search">
            </form> -->
        </div>
    </div>
</nav>
<script>
    var url = window.location.pathname;
    $('nav-item').find('a')(function () {
       $(this),toggleClass('active', $(this).attr('href')== url);
    });
</script>